### ISSUE TITLE
Bearing?

### ISSUE THREAD

**Issue by miniminne** [barryhunter/classygmaps#101]
Is there a way to add the bearing with StreetView or is that pushing what this is capable with?

**Comment by gnomontosunlight** [comment]
Street View can be used very well within KMLMap. Just be sure that under Controls "Street View (Pegman)" is ticked; it is selected by default however. Pegman can then be found in the bottom right corner. Now drag Pegman to anywhere you wish on the map. Under Layers you can choose to have Street View coverage (on the map) selected or not. Finally, you have screen controls via the drop down menu in the top right corner. There, you can also deselect the Street View screen.
