### ISSUE TITLE
Please add map outlines

### ISSUE THREAD

**Issue by LucasDMX1** [barryhunter/classygmaps#107]
In the old Google Maps when you search for a specific city or neighborhood and countries it showed an outline

example: https://www.google.co.ke/search?q=google+maps+classic+outline&biw=1360&bih=651&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiJjcj6hv_LAhXHh5AKHdwsB50Q_AUIBigB#imgrc=I6U0rt5KysgCiM%3A

**Comment by barryhunter** [comment]
Duplicate of https://github.com/barryhunter/classygmaps/issues/49
