### ISSUE TITLE
Directions don't work in UK

### ISSUE THREAD

**Issue by Dukwski** [barryhunter/classygmaps#11]
Hi
Would love it if this works as new Google maps is TRULY AWFUL, but, if I put in a place, town or postcode, it appears on the map. If I put in a from & to postcode, I get directions. If I put in a via, I get a world map
Thanks

**Comment by Anska** [comment]
Yes, also in UK and found the same problem. Direct directions work but going via just shows image of world - no directions. 
Directions: I would like the option to minimize/maximise streetview and 'mini map' when looking/exploring directions. 
Directions: Also the option to have the blue directions line to appear on the actual street view so you can 'drive' along it but I'm being picky now!!
That said....THIS IS COMPLETELY THE MOST AWESOME THING EVER!!!  Thank you so much for putting the time and effort into this. We of the world salute you. :)

**Comment by barryhunter** [comment]
Fixed :)

@Anska, I think your other points are ocvered in other reports... 

There is already an issue for condifuring streetview https://github.com/barryhunter/classygmaps/issues/1 ) 

Showing the directions in streetview, would happen with https://github.com/barryhunter/classygmaps/issues/13 if implemented

**Comment by Anska** [comment]
Fantastic Barry. You're every pattern of awesome.
Thanks for the message :)
Anska
