### ISSUE TITLE
Right clicking not working

### ISSUE THREAD

**Issue by Killerko** [barryhunter/classygmaps#111]
Any chance we could get the popup menu with "Direction to here" and "Direction from here" when right clicking on the map? Would make setting up directions a little bit easier when you don't know the exact address.

Not sure how easy this would be or if it is possible at all, but its worth asking.

**Comment by barryhunter** [comment]
Alas Directions was removed as the request of Google, as it made the site too much like the real Google Maps. 

Adding such context menu, would again be making the site more like Google Maps :(

**Comment by Killerko** [comment]
This is pretty sad.. removing this option renders the whole map kinda less useful.. isn't there any other way how you could add this without using the right click context menu? Like for example double clicking would add a point on a map which would automatically be added as your destination.. then another double click would add another point that would be added as your starting point.. then its easy to swap them in direction if you need to, or add more points, etc.. also right clicking on a point could delete it.. etc.  just an idea
