### ISSUE TITLE
Country Borders No Roads

### ISSUE THREAD

**Issue by TrashF15E** [barryhunter/classygmaps#132]
[
  {
    "elementType": "labels",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "administrative.land_parcel",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "administrative.neighborhood",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "road",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  }
]
Copy JSON

**Comment by gnomontosunlight** [comment]
Please unsubscribe from this thread.

Regards,
Jack Brouwer

---
Deze e-mail is gecontroleerd op virussen door AVG.
http://www.avg.com
