### ISSUE TITLE
print map without wording on left side of page

### ISSUE THREAD

**Issue by cagnew** [barryhunter/classygmaps#22]

**Comment by terrymap** [comment]
yes yes yes please! classic google maps printing

**Comment by mohrjo** [comment]
Yes please provide the feature of allowing the user to zoom in/out right/left to position the page that is to be printed so the user set the coverage.

**Comment by barryhunter** [comment]
I'm marking this a duplicate of 
https://github.com/barryhunter/classygmaps/issues/29

its not exactly the same request, but will consider that one a general request for better printing options.
