### ISSUE TITLE
Missing search function on a Netbook

### ISSUE THREAD

**Issue by Greebo39** [barryhunter/classygmaps#28]
There is no discernible search facility, or the rest of the top menu (Search|Directions|Options) when using an Asus Netbook with Kubuntu Linux and Firefox. There is using my Dell XPS 17 (L701X) with Ubuntu14.04 and Firefox 38.0, although the search box and top menu partially overlay the "p" of "ClassyGMap"

Edit: The Netbook displays correctly with the Rekonq Browser

**Comment by barryhunter** [comment]
Fixed. Now hide the 'logo' on narrow screens.
