### ISSUE TITLE
undo split screen?

### ISSUE THREAD

**Issue by sandpiper1** [barryhunter/classygmaps#34]
I can see where the split screen might come in handy while in street view, but I find it takes up too much space and could not find a way of undoing the split.

Ps Thank you SO much for recreating the Classic, but I have a feeling it is going to be even better!

**Comment by barryhunter** [comment]
Duplicate of https://github.com/barryhunter/classygmaps/issues/1

**Comment by sandpiper1** [comment]
Oh....sorry!
