### ISSUE TITLE
Scale thingummyjig

### ISSUE THREAD

**Issue by Muddy7** [barryhunter/classygmaps#37]
First, congratulations on the first app I've found that seems to work as well for me (almost!) as the old Google classic Maps.

My suggestion is to add the small horizontal line in the bottom left-hand corner that gives the scaled distances in km and miles. This is invaluable for estimating and/or measuring distances.

Thanks!

**Comment by Muddy7** [comment]
Sorry! I've just found the scale bar in the controls options in the left hand menu bar. So small modification to my suggestion: possibility of having this option checked by default.

Once again, I think your app ("rip-off") is brilliant!!

**Comment by Muddy7** [comment]
After further testing, I find the bigger issue is that the Scale Bar does not print correctly. I would imagine that you are already aware of this bug (perhaps this is why you don't [...yet...] have it checked by default in the control options?) but, for me, this is very important so I can estimate and/or measure distances when using printed copy on the ground.

**Comment by barryhunter** [comment]
The main reason it's not enabled by default, is frankly its rubbish. Its not very clear, and hidden away in the corner. Its like Google themselves where ashamed of it, and wanted to hide it. 

Would like to reimplement a much nicer scale bar. Bigger and clearer

... printing is definitly something not considered in ClassyGMaps yet. It could be a lot better. 


(as an aside, do be weary with the projection used by Googel Maps, the scale isn't constant. The scale at the top is different to the bottom. I dont know where on the map the scale bar presents (top/middle/bottom/other) - I guess ideal is middle would make most sence, but then again, the scale under the scale bar would be better. I think this is another reason google dont devote much to making a nice scale bar)

**Comment by Muddy7** [comment]
Now I remember, it appears on the print window on one's computer but doesn't print to the hard copy (at least not on my computers and printers). I had to add a scale bar myself based on their scale bar (I also had to proportionally adjust my bar as the size of the map on the screen was always different to that on the hard copy). Regarding micro-accuracy of the scale, that isn't such a big deal for me. Even if it has an error of as much as 10 or even 15%, that's no major hassle to me. I'm perfectly happy even with a vague idea of scale and distances when driving (cycling for me) or walking.

Having said that, a scale bar superior in accuracy and quality to Google's would of course be a feature very much to be desired.

**Comment by barryhunter** [comment]
One interesting 'alternative' to a scale bar, is a grid. For example: 
http://m.nearby.org.uk/gmap.php#ll=53.328256,-2.195358&z=12&t=r
(only works in the British Isles) 

... could make a worldwide version of that (using a UTM/MGRS grid) - which provides an implicit idea of 'scale'. 

But if did make a new a scale bar, it would more be something like
[Image example](https://www.google.co.uk/search?q=scale+bar&tbm=isch&imgil=cclqvCx3s8iFyM%253A%253BJ12T9L0CdiF-iM%253Bhttp%25253A%25252F%25252Fwww.cadblocksfree.com%25252Fdownloaddetails.php%25253Fid%2525253D3111&source=iu&pf=m&fir=cclqvCx3s8iFyM%253A%252CJ12T9L0CdiF-iM%252C_&usg=__UVPXFWo0yWItBtqZrDZ_cq5x3ew%3D&biw=1160&bih=963&ved=0CCsQyjdqFQoTCJ7539D-k8YCFRMI2wod_0sAVw&ei=Rfh_Vd7CNJOQ7Ab_l4G4BQ#imgrc=cclqvCx3s8iFyM%253A%3BJ12T9L0CdiF-iM%3Bhttp%253A%252F%252Fwww.cadblocksfree.com%252Fimages%252F1086-Scale%252520bar.png%3Bhttp%253A%252F%252Fwww.cadblocksfree.com%252Fdownloaddetails.php%253Fid%253D3111%3B1295%3B880)
... a bar along the whole bottom edge. rather than a tiny item in one corner.

**Comment by Muddy7** [comment]
I love the idea of a grid. We're all used to that method when we use traditional maps. If you can tweak a worldwide version of that, it would be great.

As I would never use Google or other internet map apps like yours for specialist uses such as for example orienteering, micro-accuracy is not an issue for me (though in the highly unlikely event that someone could come up with a free map app approximating to the same quality as, say, UK Ordnance Survey maps, that would be REALLY REALLY interesting!!).

The bar along the bottom edge is also an excellent idea.

Both are good, but personally I would definitely prefer the first, as long as it is roughly accurate for everyday non-specialist purposes.

**Comment by barryhunter** [comment]
I'm trying to clear up the list of issues, as there is lots of duplication. marking this as dupl of https://github.com/barryhunter/classygmaps/issues/37 even though this one has some intersting discussions about a grid etc.

**Comment by Muddy7** [comment]
Hi Barry.

 

Great to see you're continuing to work on this project! For me, your
ClassyGMaps is the best alternative I have found so far on the web to the
retired Classic Google Maps. I can only congratulate you on your endeavours
and will be using your app whenever I need to plan a route in future (I am a
cyclist).

 

I'm not quite sure how I can support you in this endeavour as I am currently
financially pretty strapped but please do keep me informed and meanwhile let
me know if you can see any other way I can support you.

 

Thanks for keeping us updated!

 

Keith

 

  _____

**Comment by barryhunter** [comment]
Money isnt really an issue, its time. The best way to help would be to find/recuite more developers. :)

We are trying to recreate here, something that took Google about 7-8 years to develop. They probably have/had a whole team of developers. (Although we do have some benefit of learning from their mistakes, and have access to a pretty powerful API, so we can create without too much worry about experimentation)

**Comment by Muddy7** [comment]
Hi Barry.

 

I'm afraid I'm not a computer man so I don't have many contacts of that
kind.

 

However if I do come across any likely chap (or gal!), I'll certainly spread
the gospel and encourage them to contact you.

 

Thanks for everything!

 

Keith

 

  _____
