### ISSUE TITLE
Printing with Street View imagery

### ISSUE THREAD

**Issue by AEGBRG** [barryhunter/classygmaps#45]
Is there a way to incorporate this printing feature that was in Classic Google Maps? It was great to have street view for each step, as in this picture:

![printed-classic-maps](https://cloud.githubusercontent.com/assets/13089719/8397875/4a3b3258-1da0-11e5-96f4-ba8421aa7c26.png)

If you are able to add this feature that would be amazing. Either way though, thanks Barry for what you are doing!

**Comment by barryhunter** [comment]
This is a duplicate of 
https://github.com/barryhunter/classygmaps/issues/29
