### ISSUE TITLE
Cannot change ratio of screen areas in "split screen mode"

### ISSUE THREAD

**Issue by ajburley** [barryhunter/classygmaps#50]
On the classic Google Maps, when you entered "split screen mode" (half Street View and half map), you could drag the bar separating the two areas to adjust the ratio - for example have the bottom map take up only a quarter of the screen rather than half. Seems you can't do this on ClassyGMap.

**Comment by barryhunter** [comment]
I doubt will make it draggable, but there should be a dropdown top right, to change the display, includuing a bigger portion of SV. 

Duplicates #1

**Comment by ajburley** [comment]
Okay, so for horizontal there are only two options "horizontal split" (50:50) and "horizontal bigger" (SV is bigger than map), I don't suppose you could also add one where the map is bigger than SV (opposite of "horizontal bigger")?
