### ISSUE TITLE
Can't plot a route in order to drag the curve

### ISSUE THREAD

**Issue by ajburley** [barryhunter/classygmaps#52]
Can't plot a route in ClassyGMap. One feature that is missing from the New Google Maps is the ability to drag the curve - i.e. when you have plotted a route between two points, you could drag the route to change it. This was a feature I used a lot to generate text directions based on pictoral routes, to calculate distance along a given route, and to show a picture of a specific route. On the New Google Maps you can only choose from the routes available. Please add the right-click menu to ClassyGMap to be able to get directions from/to, and then add the "drag curve" type function.

**Comment by barryhunter** [comment]
You can drag the route in the 'New' Google Maps. Although check you arent in 'Lite' mode. 

And draggable directions are also enabled in ClassyGMap. 

There is a seperate request for a right click context menu.

**Comment by ajburley** [comment]
Okay, I will defer to the separate request. I hadn't realised there was even an option to plot a route in ClassyGMap, because I have only ever done it before by right-clicking.
