### ISSUE TITLE
Add "horizontal smaller" option in street view menu

### ISSUE THREAD

**Issue by ajburley** [barryhunter/classygmaps#53]
The street view menu currently has "horizontal split" (56:44 split between SV and map - i.e. roughly equal (why is it not exactly 50:50?)) and "horizontal bigger" (75:25 split between SV and map - i.e. SV takes up much more space than the map). Suggest to also add "horizontal smaller" where the map takes up more space than the SV.

**Comment by barryhunter** [comment]
Its not 50:50 because 60px is lost at the top due to the search box. 56:44 means closer to half (or just above) is used actually used for SV.
