### ISSUE TITLE
Terrain without labels

### ISSUE THREAD

**Issue by dumlo** [barryhunter/classygmaps#61]
Dear authors, thank you for your work, but let me note that it would be a great feature to get terrain without labels. Terrain checkbox seems to be hidden when I choose "No Label" and that a pity.

**Comment by barryhunter** [comment]
I've just rewritten the map styling code, from offering distinct new map types (in the map selector top right), to be a separate distinct "Map Style" dropdown. 

As well as meaning its much easier to add more basemap styles, they also apply what ever mode you in, be it map, terrain, or satellite.

**Comment by dumlo** [comment]
Fantastic, Barry!

Thank you very much. I'm already using it!

Max
