### ISSUE TITLE
More vegetation?

### ISSUE THREAD

**Issue by T6A5** [barryhunter/classygmaps#70]
Hi there,

One of my biggest annoyances with the new Google Maps is how a lot of vegetation disappears from the map if you zoom in too close on them. To demonstrate what I mean, here are two shots, one from March 2015 and one from today:

http://i.imgur.com/8Ggwnka.png
http://i.imgur.com/WvttoIo.png

With the lack of the greenery indicated, it not only makes the map feel a lot more empty, but it's also inaccurate. How would anyone know there's a hill in said place? What if it's a factory? A housing development? A giant hole into Mordor? If at all possible, I would like to see these features restored.

Thanks for your time.

**Comment by barryhunter** [comment]
Not sure anything can do within ClassyGMaps. We only display the map Google provides, dont control what is included on the map. (although can hide specific styles of map features - but doesnt help if missing)
