### ISSUE TITLE
minor: rough clicks

### ISSUE THREAD

**Issue by egoldobin** [barryhunter/classygmaps#8]
In the left panel there are checkboxes. If you click any of them it changes the state. Even if you click the text to it, e.g. "Traffic", "Transit", "Bicycle", etc, the corresponding checkbox changes the state too, which is very convenient as you should not be very precise with your mouse.

However, this DOES NOT work for control-text like "Scale bar", "Pan", etc... -- clicking these texts will always toggle "StreetView" checkbox. huh? 

Can you, please, fix this small annoyance?

**Comment by barryhunter** [comment]
done

**Comment by egoldobin** [comment]
WOW! This was FAST! Thanks a lot! Google should really learn how to react that fast! ;-)
