### ISSUE TITLE
Feature Suggestion - Screenshot Mode

### ISSUE THREAD

**Issue by fasterfaster** [barryhunter/classygmaps#83]
Great job on ClassyGMaps.  I have one feature suggestion: Screenshot Mode.  This would remove ALL graphical overlays on the street view image so I could do a clean screenshot.

Also, two quick questions...

1. Is there a way to save options to a cookie (which I can tell my cookie manager to keep) so every time I view the site, it'll appear *exactly* the way I want it?

2. Is it possible to add the option to view the "vintage" street view images that the new Google Maps site has?  That's the *only* feature I like on the new site, because I can go back in time and see how a location looked in the past.  It wasn't in the classic Google Maps, so I suspect you can't add it, but it doesn't hurt to ask.

-- Paul

**Comment by barryhunter** [comment]
Dont think can hide that, see #86 

1. Possible yes, but just hasnt been done. Can open a seperate suggestion for that. 

2. Dont think so, this is no API to 'explore' the timeline of historic images. If know the id of a historic version, can then explore within that time-period, but with no way to discover those time-periods, its very hard to make it into a usable feature.

**Comment by barryhunter** [comment]
Ah, see 1 as been opened as #85. 

As this one technically is the same as #86, will close this one to cut down on the clutter
