### ISSUE TITLE
Distances in miles

### ISSUE THREAD

**Issue by davidmcc3** [barryhunter/classygmaps#87]
Is there a way to show journey distances in imperial units (miles)?

**Comment by barryhunter** [comment]
No there isnt right now. It just relies on the automatic selection that the API does. 

There is a feature request #72 to add the option

**Comment by davidmcc3** [comment]
Hi Barry
 
Thanks for the quick response. I did search for this but couldn’t find anything … thanks for the update.
 
Regards
David
David McCarthy
WEB-right
Websites, Copywriting, Communications
Tel: 02392 503 742 | Email: david.mccarthy@web-right.co.uk
http://word-right.co.uk | http://web-right.co.uk | Twitter: @WEBright 
If you absolutely must print this email, please make sure your printer is set to ‘Draft’ mode.  It's kinder to the environment and will also save you money!
WEB-right is a trading name of IDEAS-right Ltd | Company Reg. No. 5934818 | 5 Kensington Road | Gosport | PO12 1QY
